### PR TITLE
Add --creator flag to edit mode

### PR DESCRIPTION
**Pull request by jephdo**
I use the CLI to edit torrent files frequently, but I'd like to be able to also modify the `Created By` field in the torrent file e.g.:

<pre>
$ torf -i Top.Gun.Maverick.torrent -TSDCy -o foo.torrent  
       Name  Top.Gun.Maverick.2022.IMAX.1080p.BluRay.DDP.7.1.x264-c0kE.mkv
  Info Hash  3a4b2e6d67035bba32d27c1384e2bcb617130131
       Size  12.72 GiB
 Created By  qBittorrent v4.3.9
    Private  yes
 Piece Size  2 MiB
Piece Count  6513
 File Count  1
      Files  Top.Gun.Maverick.2022.IMAX.1080p.BluRay.DDP.7.1.x264-c0kE.mkv [12.72 GiB]
$ torf -i Top.Gun.Maverick.torrent -TSDCy -o foo.torrent <b>--creator</b>
       Name  Top.Gun.Maverick.2022.IMAX.1080p.BluRay.DDP.7.1.x264-c0kE.mkv
  Info Hash  3a4b2e6d67035bba32d27c1384e2bcb617130131
       Size  12.72 GiB
 <b>Created By  torf 5.0.0</b>
    Private  yes
 Piece Size  2 MiB
Piece Count  6513
 File Count  1
      Files  Top.Gun.Maverick.2022.IMAX.1080p.BluRay.DDP.7.1.x264-c0kE.mkv [12.72 GiB]
</pre>

You can manually specify a creator with `--creator, -a`, but supplying no arguments defaults to using `torf`

Test output:
```
(env) ~/workspace/torf-cli$ pytest tests/test_edit.py
================================= test session starts ==================================
platform linux -- Python 3.9.2, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/jephdo/workspace/torf-cli
collected 37 items                                                                     

tests/test_edit.py .....................................                         [100%]

================================== 37 passed in 0.22s ==================================
```

### CODE REVIEW

**Comment by rndusr** [comment]
Thank you. Very nice PR. You even wrote tests!

Unfortunately, I'm not sure this is a good idea. Why do you need to change this
field?

The "created by" field is not part of BEP3, but the inofficial spec on
theory.org says it's for the "name and version of the program used to create the
.torrent".

https://wiki.theory.org/BitTorrentSpecification#Metainfo_File_Structure

If I create a torrent with qBittorrent and change its creator to torf, what's
the point of this field in the first place?

If course, I can always change the field with any advanced text editor, but if
we add a --creator option, it suggests that you are supposed to change it, which
I think you are not.

But I'm curious about your use case.

**Comment by rndusr** [comment]
The "created by" field is not part of the "info" dictionary and therefore
doesn't change the hash. I've added --xseed to only change the info hash.

I don't have a problem with editing torrents in general. All the examples you
gave can already be edited. I was specifically asking about your use case for
editing the "created by" field.

**Comment by jephdo** [comment]
Changing `created by` is just cosmetic for me. Feel free to decline the PR tho no worries :)

Here is an irl example that motivated this PR:
```
$ torf -i Mary.Poppins.1964.1080p.BluRay.DTS.x264-EbP.torrent
       Name  Mary.Poppins.1964.1080p.BluRay.x264-EbP
  Info Hash  723a9bac953b3f3592407bf986291fd63a6aedbb
       Size  17.69 GiB
    Comment  Torrent created for 'filelist.io' tracker
    Created  2020-09-26 06:02:00
 Created By  FL Team
 ...
```
If I posted this to another tracker as is, the vestigial values for `Created By` and `Comment` would be confusing 

I currently just use `-A` to completely strip the Created By field, but I just thought it'd be nice to replace this with something meaningful like `torf 5.0.0`

**Comment by rndusr** [comment]
OK, fixing bad "created by" values sounds more reasonable.
I hadn't thought about that.
I'll think about it some more.

**Comment by rndusr** [comment]
Alright, I decided to accept this PR.

Partially because I already invested some time and because you did too, but also
because fixing bad "created by" fields seems like reasonable use case.

Thanks again for your contribution and for convincing me.

**Pull request closed without merging**
